 var initcards =  [
 {name: "Hängebrücke", Aktion: "Die Hängebrücke kannst du mit vollem Inventar nicht überqueren. Lege Dinge dazu auf ihr Feld zurück.", warn:"Edelstein", bgc: "gelb" },
 {name: "Hängebrücke", Aktion: "Die Hängebrücke kannst du mit vollem Inventar nicht überqueren. Lege Dinge dazu auf ihr Feld zurück.", warn:"Edelstein", bgc: "gelb" },
 {name: "Hängebrücke", Aktion: "Die Hängebrücke kannst du mit vollem Inventar nicht überqueren. Lege Dinge dazu auf ihr Feld zurück.", warn:"Edelstein", bgc: "gelb" },
 {name: "Hängebrücke", Aktion: "Die Hängebrücke kannst du mit vollem Inventar nicht überqueren. Lege Dinge dazu auf ihr Feld zurück.", warn:"Edelstein", bgc: "gelb" },
 {name: "Kannibale", Aktion: "Die Kannibalen verfolgen dich. Du hast das Idol oder gibst einen Gegenstand ab, sonst töten sie dich.", warn:"Edelstein"},
 {name: "Kannibale", Aktion: "Die Kannibalen verfolgen dich. Du hast das Idol oder gibst einen Gegenstand ab, sonst töten sie dich.", warn:"Edelstein"},
 {name: "Kannibale", Aktion: "Die Kannibalen verfolgen dich. Du hast das Idol oder gibst einen Gegenstand ab, sonst töten sie dich.", warn:"Edelstein"},
 {name: "Kannibale", Aktion: "Die Kannibalen verfolgen dich. Du hast das Idol oder gibst einen Gegenstand ab, sonst töten sie dich.", warn:"Edelstein", pagebreak: "pagebreak"},
 {name: "Schwarze Kugel", Aktion: "Du findest eine schwarze Kugel.", imgclass:"symbol",ver: "true"},
 {name: "Schlüssel", Aktion: "Ein merkwürdig geformter Schlüssel.", imgclass:"symbol",ver: "true"},
 {name: "Weiße Kugel", Aktion: "Du findest eine weiße Kugel. Bringe alle 4 Teile nach Hause", imgclass:"symbol",hor: "true"},
 {name: "Boot", Aktion: "Bring das Boot zum Fluss, um das Abenteuer zu beenden.", hor: true, imgclass:"bigsymbol"},
 {name: "Fluss", color : "H", Aktion: " Du kannst das Abenteuer mit dem Boot am Fluss verlassen. Hier darfst du beliebige Gegenstände ablegen.", warn:"Boot", bgc:"blue"},
 {name: "Rucksack", Aktion: "Mit dem Rucksack kannst du 3 Dinge mehr tragen.",ver: "true", imgclass:"symbol"},
 {name: "Fels", Aktion: "Du kannst dieses Feld nicht betreten und nicht mit der Liane überfliegen."},
 {name: "Fels", Aktion: "Du kannst dieses Feld nicht betreten und nicht mit der Liane überfliegen."},
 {name: "Dynamit", Aktion: "Mit dem Dynamit kannst du einen Felsen sprengen. Lege das Dynamit dazu auf den Felsen."},
 {name: "Machete", Aktion: "Die Machete kann eine Dschungelwand öffnen. Lege die Machete dazu auf die Wand.",ver: "true", imgclass:"symbol"},
 {name: "Machete", Aktion: "Die Machete kann eine Dschungelwand öffnen. Lege die Machete dazu uf die Wand.",hor: "true",imgclass:"symbol"},
 {name: "Machete", Aktion: "Die Machete kann eine Dschungelwand öffnen. Lege die Machete dazu auf die Wand.",hor: "true", imgclass:"symbol"},
 {name: "Machete", Aktion: "Die Machete kann eine Dschungelwand öffnen. Lege die Machete dazu auf die Wand.",hor: "true", imgclass:"symbol"},
 {name: "Machete", Aktion: "Die Machete kann eine Dschungelwand öffnen. Lege die Machete dazu auf die Wand.",hor: "true", imgclass:"symbol"},
 {name: "Liane", Aktion: "Mit der Liane kann man einmal waagrecht oder senkrecht beliebig weit auf ein offenes Feld springen.",ver: "true", imgclass:"symbol"},
 {name: "Liane", Aktion: "Mit der Liane kann man einmal waagrecht oder senkrecht beliebig weit auf ein offenes Feld springen.",hor: "true",ver: "true", imgclass:"symbol"},
 {name: "Liane", Aktion: "Mit der Liane kann man einmal waagrecht oder senkrecht beliebig weit auf ein offenes Feld springen.",hor: "true", imgclass:"symbol"},
 {name: "Höhle", Aktion: "Nur mit der Fackel kann man durch die Höhle direkt zu anderen Höhlen gehen.",ver: "true", warn:"Fackel" , bgc:"blue"},
 {name: "Höhle", Aktion: "Nur mit der Fackel kann man durch die Höhle direkt zu anderen Höhlen gehen.",ver: "true", warn:"Fackel" , bgc:"blue"},
 {name: "Höhle", Aktion: "Nur mit der Fackel kann man durch die Höhle direkt zu anderen Höhlen gehen.",ver: "true", warn:"Fackel" , bgc:"blue"},
 {name: "Höhle", Aktion: "Nur mit der Fackel kann man durch die Höhle direkt zu anderen Höhlen gehen.",hor: "true", warn:"Fackel" , bgc:"blue"},
 {name: "Fackel", Aktion: "Mit der Fackel kann man durch die Höhlen gehen.",ver: "true", imgclass:"symbol", pagebreak: "pagebreak"},
 {name: "Pistole", Aktion: "Die Pistole ist alt und hat keine Munition.",hor: "true",ver: "true", imgclass:"symbol", bgc: "gelb"},
 {name: "Weg", Aktion: "Jane: Ist das der richtige Weg?",hor: "true"},
 {name: "Weg", Aktion: "Jack: Hier können wir rasten.",hor: "true"},
 {name: "Weg", Aktion: "Jane: Hier waren wir doch schon mal.",hor: "true", pagebreak: "pagebreak"},
 {name: "Weg", Aktion: ""},
 {name: "Weg", Aktion: ""},
 {name: "Weg", Aktion: "",hor: "true"},
 {name: "Weg", Aktion: "",ver: "true"},
 {name: "Weg", Aktion: "",ver: "true"},
 {name: "Weg", Aktion: "",ver: "true"},
 {name: "Weg", Aktion: "",ver: "true"},
 {name: "Weg", Aktion: "",ver: "true"},
 {name: "Weg", Aktion: "",ver: "true"},
 {name: "Weg", Aktion: "",hor: "true"}
 ];

 var initActions = [
 {name: "Jäger", Aktion: "Der Jäger hat versucht den Schatz der Kannibalen zu stehlen und diesen Frevel mit seinem Leben bezahlt. Die Kannibalen sind sehr wütend und töten jeden den Sie begegnen.", bgc:"orange", win:"Fluss", bgcwin:"blue",task: true},
 {name: "Kannibalen", color : "H", Aktion: "Die Kannibalen sind eigentlich friedliebend und bewachen das Tal. Du kannst ungehindert an Ihnen vorbeilaufen.", win:"Jane2", bgcwin:"green", task: true},
 {name: "Jane", Aktion: "Jane hat sich in dich verliebt. Sie will bei dir bleiben. ",win:"Fluss", bgcwin:"blue", warn:"Jane2", bgc:"orange", task: true},
 {name: "Höhle", Aktion: "Die Höhle enthält den Schatz, der von den Kannibalen verehrt wird. Durch diese Höhle könnt ihr mit der Fackel direkt zu anderen Höhlen ziehen. ",win:"Fluss", bgcwin:"blue", warn:"Jane2", bgc:"orange", task: true},
 {name: "Raumschiff", Aktion: "Da Raumschiff erklärt den Ursprung der Zivilisation Mu. Die Ausserirdischne Besitzer sind alle verschollen. Mit dem Schlüssel könnt ihr das Schiff starten und das Abenteuer beenden.",win:"Fluss", bgcwin:"blue", warn:"Jane2", bgc:"orange", task: true},
 {name: "Prof. Hampton", Aktion: "Janes Vater lebt glücklich und zufrieden bei den Kannibalen. Wenn du ihm beide Kugeln bringst, verlässt er mit euch das Tal.",hor: "true", imgclass:"symbol", task: true}
 ];


 var start = {name: "Akt III", color : "H", 
 Aktion: "Ihr betretet das verschollene Tal. Hier muss sich Prof. Hampton befinden. Vielleicht ist er noch am Leben?"};