 var initcards =  [
 {name: "Hängebrücke", Aktion: "Die Hängebrücke kannst du mit 4 Dingen im Inventar nicht überqueren. Lege Dinge dazu auf ihr Feld zurück.", warn:"Edelstein", bgc: "gelb" },
 {name: "Hängebrücke", Aktion: "Die Hängebrücke kannst du mit 4 Dingen im Inventar nicht überqueren. Lege Dinge dazu auf ihr Feld zurück.", warn:"Edelstein", bgc: "gelb" },
 {name: "Hängebrücke", Aktion: "Die Hängebrücke kannst du mit 4 Dingen im Inventar nicht überqueren. Lege Dinge dazu auf ihr Feld zurück.", warn:"Edelstein", bgc: "gelb" },
 {name: "Hängebrücke", Aktion: "Die Hängebrücke kannst du mit 4 Dingen im Inventar nicht überqueren. Lege Dinge dazu auf ihr Feld zurück.", warn:"Edelstein", bgc: "gelb" },
 {name: "Schlange", Aktion: "Die Schlange hat ein tödliches Gift und beisst dich. Lege ein Gegengift hier ab, um vor der Schlange geschützt zu sein.", warn:"Gegengift",hor: "true"},
 {name: "Schlange", Aktion: "Die Schlange hat ein tödliches Gift und beisst dich. Lege ein Gegengift hier ab, um vor der Schlange geschützt zu sein.", warn:"Gegengift",ver: "true"},
 {name: "Schlange", Aktion: "Die Schlange hat ein tödliches Gift und beisst dich. Lege ein Gegengift hier ab, um vor der Schlange geschützt zu sein.", warn:"Gegengift"},
 {name: "Schlange", Aktion: "Die Schlange hat ein tödliches Gift und beisst dich. Lege ein Gegengift hier ab, um vor der Schlange geschützt zu sein.", warn:"Gegengift"},
 {name: "Artefakt", Aktion: "Du findest ein Artefakt der Zivilisation Mu. Bringe alle 4 Teile zum Taleingang", imgclass:"symbol",ver: "true"},
 {name: "Artefakt", Aktion: "Du findest ein Artefakt der Zivilisation Mu. Bringe alle 4 Teile zum Taleingang", imgclass:"symbol",hor: "true"},
 {name: "Artefakt", Aktion: "Du findest ein Artefakt der Zivilisation Mu. Bringe alle 4 Teile zum Taleingang", imgclass:"symbol",ver: "true"},
 {name: "Artefakt", Aktion: "Du findest ein Artefakt der Zivilisation Mu. Bringe alle 4 Teile zum Taleingang", imgclass:"symbol",hor: "true"},
 {name: "Taleingang", Aktion: "Mit den 4 Artefakten kannst du den Eingang zum verschollenen Tal der Mu öffnen. und beendest Akt II. Du kannst die Artefakte hier ablegen.",hor: "true", bgc:"green"},
 {name: "Rucksack", Aktion: "Mit dem Rucksack kannst du 3 Dinge mehr tragen.",ver: "true", imgclass:"symbol"},
 {name: "Gegengift", Aktion: "Das Gegengift schützt dich vor einer Schlange. ",hor: "true", imgclass:"symbol"},
 {name: "Gegengift", Aktion: "Das Gegengift schützt dich vor einer Schlange. ",ver: "true", imgclass:"symbol"},
 {name: "Machete", Aktion: "Die Machete kann eine Dschungelwand öffnen. Lege die Machete dazu auf die Wand.",ver: "true", imgclass:"symbol"},
 {name: "Machete", Aktion: "Die Machete kann eine Dschungelwand öffnen. Lege die Machete dazu auf die Wand.",ver: "true",imgclass:"symbol"},
 {name: "Machete", Aktion: "Die Machete kann eine Dschungelwand öffnen. Lege die Machete dazu auf die Wand.",hor: "true", imgclass:"symbol"},
 {name: "Machete", Aktion: "Die Machete kann eine Dschungelwand öffnen. Lege die Machete dazu auf die Wand.",hor: "true", imgclass:"symbol"},
 {name: "Fels", Aktion: "Du kannst dieses Feld nicht betreten und nicht mit der Liane überfliegen."},
 {name: "Liane", Aktion: "Mit der Liane kann man einmal waagrecht oder senkrecht beliebig weit auf ein offenes Feld springen.",ver: "true", imgclass:"symbol"},
 {name: "Liane", Aktion: "Mit der Liane kann man einmal waagrecht oder senkrecht beliebig weit auf ein offenes Feld springen.",hor: "true",ver: "true", imgclass:"symbol"},
 {name: "Liane", Aktion: "Mit der Liane kann man einmal waagrecht oder senkrecht beliebig weit auf ein offenes Feld springen.",hor: "true", imgclass:"symbol"},
 {name: "Höhle", Aktion: "Nur mit der Fackel kann man durch die Höhle direkt zu anderen Höhlen gehen.",ver: "true", warn:"Fackel" , bgc:"blue"},
 {name: "Höhle", Aktion: "Nur mit der Fackel kann man durch die Höhle direkt zu anderen Höhlen gehen.",ver: "true", warn:"Fackel" , bgc:"blue"},
 {name: "Höhle", Aktion: "Nur mit der Fackel kann man durch die Höhle direkt zu anderen Höhlen gehen.",ver: "true", warn:"Fackel" , bgc:"blue"},
 {name: "Höhle", Aktion: "Nur mit der Fackel kann man durch die Höhle direkt zu anderen Höhlen gehen.",hor: "true", warn:"Fackel" , bgc:"blue"},
 {name: "Lager", Aktion: "Im Lager des Jäger findest du die Artifakte, die dir der Jäger genommen hat.",hor: "true", bgc:"green"},
 {name: "Fackel", Aktion: "Mit der Fackel kann man durch die Höhlen gehen.",ver: "true", imgclass:"symbol", pagebreak: "pagebreak"},
 {name: "Pistole", Aktion: "Die Pistole ist alt und hat keine Munition.",hor: "true",ver: "true", imgclass:"symbol", bgc: "gelb"},
 {name: "Weg", Aktion: "",hor: "true"},
 {name: "Weg", Aktion: "",hor: "true"},
 {name: "Weg", Aktion: "",hor: "true", pagebreak: "pagebreak"},
 {name: "Weg", Aktion: ""},
 {name: "Weg", Aktion: ""},
 {name: "Weg", Aktion: "",hor: "true"},
 {name: "Weg", Aktion: "",ver: "true"},
 {name: "Weg", Aktion: "",ver: "true"},
 {name: "Weg", Aktion: "",ver: "true"},
 {name: "Weg", Aktion: "",ver: "true"},
 {name: "Weg", Aktion: "",ver: "true"},
 {name: "Weg", Aktion: "",ver: "true"},
 {name: "Weg", Aktion: "",hor: "true"}
 ];

 var initActions = [
 {name: "Treibsand", Aktion: "Auf der Flucht vor einem Löwen trittst du in Treibsand. Jane kann dich mit einer Liane retten. Bis sie eine Liane zu dir gebracht hat, hat sie eine Zugweite von 5 und kann keine anderen Dinge nehmen.", warn:"Liane", bgcwin:"green" , bgc:"blue", task: true},
 {name: "Jäger", Aktion: "Der Jäger klaut dir alle Artefakte und bringt sie zu seinem Lager. Mit der Pistole kannst du sie ihm dort abnehmen.",warn:"Pistole", bgc:"orange", win:"Fluss", bgcwin:"blue",task: true},
 {name: "Kannibalendorf", color : "H",Aktion: "Jane wird von den Kannibalen gefangengenommen. Du kannst Sie erst in Akt III befreien.", warn:"Voodoopuppe", win:"Jane2", bgcwin:"green", task: true},
 {name: "Elfenbein", Aktion: "Im Elefantenfriedhof findest du Elfenbein. Für den Zugang benötigst du die Machete.",warn:"Machete", win:"Elfenbein", bgcwin:"green", imgclass:"symbol", task: true},
 {name: "Diamantenmine", color : "H",Aktion: "Du findest in der dunklen Mine grosse Diamenten. Bein Herausholen verlierst du die Fackel.", warn:"Fackel", win:"Diamantenmine", bgcwin:"green", imgclass:"symbol", task: true},
 {name: "Karte", color : "H",Aktion: "Du findest eine Karte des Dschungels. Ab sofort kannst du Karten auch diagonal anlegen.", task: true},
 {name: "Sturm", color : "H",Aktion: "Ein Sturm zieht durch den Dschungel. Alle verwendeten Macheten kommen auf Machetenfelder zurück.", task: true},
 {name: "Tiger", color : "H",Aktion: "Ein Tiger überrascht euch und jagt euch quer durch den Dschungel auf ein leeres Feld. Lege eine Karte vom Stapel auf dieses Feld.", task: true},
 ];

 var initActionsIII = [
 {name: "Jäger", Aktion: "Der Jäger klaut dir zwei Dinge (deiner Wahl) und bringt sie zum Tempel. Mit der Pistole kannst du das verhindern.",warn:"Pistole", bgc:"orange", win:"Fluss", bgcwin:"blue",task: true},
 {name: "Voodoopuppe", Aktion: "Die verlorene Voodoopuppe der Kannibalen.",ver: "true", imgclass:"symbol"},
 {name: "Tarzan", Aktion: "Jane verliebt sich in Tarzan und bleibt bei ihm. Am Ende fährt sie mit dir über den Fluss zurück.",win:"Fluss", bgcwin:"blue", warn:"Jane2", bgc:"orange", task: true},
 {name: "Tagebuch", Aktion: "Das Tagebuch enthält Aufzeichnungen. Lege eine offene Karte zurück in den Stapel und mische diesen.",ver: "true", imgclass:"symbol", task: true},
 {name: "Idol", Aktion: "Mit dem Idol kannst du die Kannibalen verjagen und an Ihnen vorbeilaufen.",hor: "true", imgclass:"symbol", task: true},
 {name: "Elfenbein", Aktion: "Im Elefantenfriedhof findest du Elfenbein. Für den Zugang benötigst du eine Machete. Gib diese ab.",warn:"Machete", win:"Elfenbein", bgcwin:"green", imgclass:"symbol", task: true},
 {name: "Treibsand", Aktion: "Dein Partner fällt in den Treibsand. Du kannst ihn nur mit einer Liane retten. Bis dahin kannst du keine anderen Dinge nehmen.", warn:"Liane", bgcwin:"green" , bgc:"blue", task: true},
 {name: "Diamantenmine", color : "H",Aktion: "Du findest in der dunklen Mine grosse Diamenten. Bein Herausholen verlierst du die Fackel.", warn:"Fackel", win:"Diamantenmine", bgcwin:"green", imgclass:"symbol", task: true},
 {name: "Lager", color : "H",Aktion: "Du findest ein verlassenes Lager. Du kannst bis zu 2 leere Dingfelder aus dem Vorrat wieder auffüllen.", warn:"Edelstein", bgc:"green", win:"Edelstein", bgcwin:"green", task: true},
 {name: "Karte", color : "H",Aktion: "Du findest eine Karte des Dschungels. Ab sofort kannst du Karten auch diagonal anlegen.", task: true},
 {name: "Sturm", color : "H",Aktion: "Ein Sturm zieht durch den Dschungel. Alle verwendeten Macheten kommen auf Machetenfelder zurück.", task: true},
 {name: "Kannibalendorf", color : "H",Aktion: "Jane wird von den Kannibalen gefangengenommen. Mit der Voodoopuppe kannst du Jane befreien.", warn:"Voodoopuppe", win:"Jane2", bgcwin:"green", task: true}
 ];


 var start = {name: "Akt II", color : "H", 
 Aktion: "Mit den Hieroglyphen findet ihr die Stelle im Dschungel an der Prof Hampton verschwunden ist. Sucht nach dem Zugang zum verschollenen Tal."};