var dataform = [
       {type:"Form", name:"mindestens so gross wie eine Katze"},
       {type:"Form", name:"kleiner als ein Esstisch"},
       {type:"Form", name:"grösser als ein Haus"},
       {type:"Form", name:"passt in eine quadratische Kiste mit 1 Meter Seitenlänge"},
       {type:"Form", name:"kann man in eine Weinflassche giessen/ schieben"},
       {type:"Form", name:"ist lang und dünn, stabförmig"},
       {type:"Form", name:"ist im wesentlichen flach"},
       {type:"Form", name:"ist im wesentlichen röhrenförmig"},
       {type:"Form", name:"ist kugel- oder eiförmig"},
       {type:"Form", name:"ist Kiste oder rechteckig"},
       {type:"Form", name:"'Vorne' und 'hinten' sind hier kaum unterscheidbar"},
       {type:"Form", name:"steht mit 4 Berührungspunkten auf dem Boden"},
       {type:"Form", name:"mit vielen Unregelmässigkeiten (Noppen, Dellen, Nasen)"},
       {type:"Form", name:"mit Loch, durch das man durchschauen kann"},
       {type:"Form", name:"mit Rad oder vollständig beweglichem Teil"},
       {type:"Form", name:"mit Gelenk oder beweglichem Teil"},
       {type:"Form", name:"mit Verzweigungen, Gabelungen, Asten, Extremitäten"},
       {type:"Form", name:"aus merhreren Teilen, evtl. miteinander verbunden"},
       {type:"Form", name:"ist spitz, man kann sich damit in den Finger stechen"},
];

var datainhalt = [
       {type:"Inhalt", name:"ist 10kg oder schwerer"},
       {type:"Inhalt", name:"ist 10kg oder leichter"},
       {type:"Inhalt", name:"enthält Glas oder durchsichtiges Material"},
       {type:"Inhalt", name:"enthält Stein"},
       {type:"Inhalt", name:"enthält Holz oder Äste"},
       {type:"Inhalt", name:"besteht aus Papier, Karton oder Stroh"},
       {type:"Inhalt", name:"hat Hörner oder Zähne"},
       {type:"Inhalt", name:"hat ein Gehirn, Mechanik oder CPU"},
       {type:"Inhalt", name:"enthält Zähflüssiges, Schleimiges oder Klebriges"},
       {type:"Inhalt", name:"enthält Kugelförmiges"},
       {type:"Inhalt", name:"besteht teilweise aus Tuch oder Stoff"},
       {type:"Inhalt", name:"hat Haare"},
       {type:"Inhalt", name:"hat innen Weichteile"},
       {type:"Inhalt", name:"ist steif, kann brechen"},
];
var dataort = [
       {type:"Ort", name:"ist nicht im Umkreis von 80 Metern zu finden"},
       {type:"Ort", name:"in diesem Land gibt es sehr viele"},
       {type:"Ort", name:"gibt es auch im Wald oder Feld"},
       {type:"Ort", name:"gab es schon bei den alten Griechen"},
       {type:"Ort", name:"ist oft im Büro"},
       {type:"Ort", name:"gibt es bei mir zu Hause"},
       {type:"Ort", name:"kann ich innerhalb von 5 Minuten hierherbringen"},
       {type:"Ort", name:"kenne ich aus einem Märchen oder der Bibel"},
       {type:"Ort", name:"gibt es in einem Wild West Film"},
       {type:"Ort", name:"gibt in einer Sportanlage"},
       {type:"Ort", name:"gibt es im Supermarkt"},
       {type:"Ort", name:"gibt es in der Stadt"},
       {type:"Ort", name:"tragen Menschen bei sich"},
       {type:"Ort", name:"wird meist im Winter verwendet"},
       {type:"Ort", name:"wird meist im Sommer verwendet"},
       {type:"Ort", name:"es gibt weniger davon als vor 100 Jahren"},
       {type:"Ort", name:"haben alle hier schon in der Hand gehabt"},
];
var dataextra = [
       {type:"Extra", name:"schwimmt im Wasser oben"},
       {type:"Extra", name:"gibt es in unterschiedlichen Farben"},
       {type:"Extra", name:"fühlt sich glatt an"},
       {type:"Extra", name:"glänzt, strahlt oder leuchtet"},
       {type:"Extra", name:"macht Geräusche, selbständig oder bei normalen Gebrauch"},
       {type:"Extra", name:"Schmilzt im Feuer"},
       {type:"Extra", name:"wächst"},
       {type:"Extra", name:"sollte man gelegentlich waschen, putzen"},
       {type:"Extra", name:"kann Wasser aufsaugen"},
       {type:"Extra", name:"tritt meist in größeren Mengen auf"},
       {type:"Extra", name:"geht kaputt, wenn man sich darauf setzt"},
       {type:"Extra", name:"kann sich selbständig bewegen"},
       {type:"Extra", name:"riecht eher gut, duftet"},
       {type:"Extra", name:"riecht eher schlecht, stinkt"},
       {type:"Extra", name:"riecht gar nicht"},
       {type:"Extra", name:"schmeckt gut"},
       {type:"Extra", name:"schmeckt schlecht"},
       {type:"Extra", name:"schmeckt nach gar nichts"},
       {type:"Extra", name:"wird nach einmaligem Gebrauch oft weggeworfen"},
       {type:"Extra", name:"wird am Fliessband produziert"},
       {type:"Extra", name:"kostet weniger als 20 Euro"},
       {type:"Extra", name:"war früher teurer oder wertvoller als heute"},
       {type:"Extra", name:"kann ohne Elektrizität kaum verwendet werden"},
       {type:"Extra", name:"darauf sind manchmal Buchstaben oder Zahlen"},
       {type:"Extra", name:"gibt es in Miniatur als Spielzeug"},
];