var datawas = [
       {type:"was", name:"ist steif, kann brechen"},
       {type:"was", name:"ist schwerer als ein Ziegelstein"},
       {type:"was", name:"ist leichter als ein Kühlschrank"},
       {type:"was", name:"enthält Kork, Schnur, Gummi oder Wachs"},
       {type:"was", name:"ist teilweise aus Stein, Prozellan oder Glas"},
       {type:"was", name:"hat Tasten, Pedal oder Knöpfe"},
       {type:"was", name:"besteht hauptsächlich aus Holz"},
       {type:"was", name:"besteht aus Papier, Karton oder Stroh"},
       {type:"was", name:"hat Rüssel, Hörner, Schnabel, Zähne oder Schwanz"},
       {type:"was", name:"hat Auge, Linse, Fenster oder Bildschirm"},
       {type:"was", name:"kann man kneten oder zerknüllen, one dass es kaputt geht"},
       {type:"was", name:"hat ein Gehirn, Mechanik oder CPU"},
       {type:"was", name:"hat Mund, Loch oder Eingang"},
       {type:"was", name:"hat Blätter,Federn oder abnehmbare Teile"},
       {type:"was", name:"ist zähflüssig, teigig, schleimig oder klebrig"},
       {type:"was", name:"besteht teilweise aus Wolle, Tuch oder Stoff"},
       {type:"was", name:"glänzt, strahlt oder leuchtet"},
       {type:"was", name:"hat Haut, Fell, Schuppen oder Schale"},
       {type:"was", name:"hat Beine, Arme oder Gelenke"},
       {type:"was", name:"hat innen Weichteile"},

];
var datawie = [
       {type:"wie", name:"kann von starkem Winde verweht werden. (kein Sturm)"},
       {type:"wie", name:"mindestens so gross wie eine Katze"},
       {type:"wie", name:"kann man in eine Weinflassche giessen/ schieben"},
       {type:"wie", name:"man kann sich damit in den Finger stechen oder schneiden"},
       {type:"wie", name:"ist lang und dünn"},
       {type:"wie", name:"ist hauptsächlich rund"},
       {type:"wie", name:"'Vorne' und 'hinten' sind hier kaum unterscheidbar"},
       {type:"wie", name:"ist im wesentlichen flach"},
       {type:"wie", name:"fühlt sich glatt an"},
       {type:"wie", name:"macht Geräusche, selbständig oder bei normalen Gebrauch"},
       {type:"wie", name:"tritt meist in größeren Mengen auf"},
       {type:"wie", name:"geht kaputt, wenn man sich darauf setzt"},
       {type:"wie", name:"kann sich selbständig bewegen"},
       {type:"wie", name:"riecht man"},
       {type:"wie", name:"ist oft wärmer als die Umgebung"},
       {type:"wie", name:"hat ungefähr die Form eines Quaders (rechteckig)"},
       {type:"wie", name:"steht mit 4 Berührungspunkten auf dem Boden"},
       {type:"wie", name:"gibt es in unterschiedlichen Farben"},
       {type:"wie", name:"schwimmt im Wasser oben"},
       {type:"wie", name:"Schmilzt im Feuer"},
       {type:"wie", name:"wächst"},
       {type:"wie", name:"teilweise mit grüner Farbe"},
       {type:"wie", name:"teilweise mit gelber Farbe"},
       {type:"wie", name:"teilweise mit roter Farbe"},
       {type:"wie", name:"teilweise mit blauer Farbe"},
       {type:"wie", name:"sollte man gelegentlich waschen, putzen"},
       {type:"wie", name:"lässt sich vollständig verbrennen"},
       {type:"wie", name:"ist nach 1 Stunde im Wasser aufgelöst oder aufgeweicht"},
       {type:"wie", name:"kann man so fotografieren, dass es viereckig scheint"},
       {type:"wie", name:"geht nach einem Tag in der Tiefkühltruhe kaputt"},
       {type:"wie", name:"kann Wasser aufsaugen"},
];
var datawo = [
       {type:"wo", name:"ist nicht im Umkreis von 80 Metern zu finden"},
       {type:"wo", name:"Teil unserer Zivilisation"},
       {type:"wo", name:"gab es schon bei den alten Griechen"},
       {type:"wo", name:"ist oft im Büro"},
       {type:"wo", name:"gibt es auch im Wald oder Feld"},
       {type:"wo", name:"kann ich innerhalb von 5 Minuten hierherbringen"},
       {type:"wo", name:"gibt es bei mir zu Hause"},
       {type:"wo", name:"kenne ich aus einem Märchen oder der Bibel"},
       {type:"wo", name:"gibt es in einem Wild West Film"},
       {type:"wo", name:"gibt in einer Sportanlage"},
       {type:"wo", name:"gibt es im Supermarkt"},
       {type:"wo", name:"habe ich in diesem Jahr noch nicht gesehen"},
       {type:"wo", name:"tragen Menschen an sich"},
       {type:"wo", name:"wird meist im Winter verwendet"},
       {type:"wo", name:"es gibt weniger davon als vor 100 Jahren"},
];
var datawofür = [
       {type:"wofür", name:"wird zur Dekoration verwendet"},
       {type:"wofür", name:"kann man essen, ohne zu sterben"},
       {type:"wofür", name:"ist der Rest, der nach Gebrauch übrigbleibt."},
       {type:"wofür", name:"wird nach einmaligem Gebrauch oft weggeworfen"},
       {type:"wofür", name:"überdauert Jahrzehnte"},
       {type:"wofür", name:"haben alle hier schon in der Hand gehabt"},
       {type:"wofür", name:"spricht, kommuniziert oder hat was mit Kommunikation zu tun"},
       {type:"wofür", name:"wird am Fliessband produziert"},
       {type:"wofür", name:"kostet weniger als 20 Euro"},
       {type:"wofür", name:"war früher teurer oder wertvoller als heute"},
       {type:"wofür", name:"kann für Kleinkinder gefährlich sein"},
       {type:"wofür", name:"kommt in Sprichwort oder Werbeslogan vor"},
       {type:"wofür", name:"kann ohne Elektrizität kaum verwendet werden"},
       {type:"wofür", name:"darauf sind manchmal Buchstaben oder Zahlen"},
       {type:"wofür", name:"gibt es in Miniatur als Spielzeug"},
];