var data = [
	"fühlt sich schwer an",
	"kann man kneten oder zerknüllen",
	"kann man vollständig in eine Weinflassche giessen/ schieben",
	"mondestens so gross wie eine Katze",
	"enthält Kork, Schnur, Gummi oder Wachs",
	"ist teilweise aus Stein, Prozellan oder Glas",
	"hat Tasten, Pedal oder Knöpfe",
	"besteht aus Papier, Karton oder Stroh",
	"hat Rüssel, Hörner, Schnabel, Zähne oder Schwanz",
	"hat Auge, Linse, Fenster oder Bildschirm",
	"ist zähflüssig, schleimig oder klebrig",
	"hat Haut, Fell, Schuppen oder Schale",
	"man kann sich damit in den Finger stechen",
	"ist lang und dünn",
	"ist hauptsächlich rund",
	"ist nach 1 Stunde im Wasser aufgelöst oder aufgeweicht",
	"kann man essen, ohne zu sterben",
	"ist aussen manchmal grün",
	"ist so schwer wie ich",
	"schwimmt im Wasser oben",
	"hat ein Gehirn, Mechanik oder CPU",
	"glänzt, strahlt oder leuchtet",
	"hat Beine",
	"hat Löcher",
	"Schmilzt im Feuer",
	"wächst",
	"hat Blätter oder Federn",
	"ist steif, kann brechen",
	"sollte man gelegentlich waschen, putzen",
	"hat ein Loch oder Eingang",
	"besteht hauptsächlich aus Holz",
	"lässt sich vollständig verbrennen",
	"besteht teilweise aus Wolle, Tuch oder Stoff",
	"fühlt sich glatt an",
	"kann Wasser aufsaugen",
	"hat innen Weichteile",
	"ist im wesentlichen flach",

	"ist nicht im Umkreis von 80 Metern zu finden",
	"kann man so fotografieren, dass es viereckig scheint",
	"fliegt oder schwebt vom Winde verweht",
	"wird oft weggeworfen",
	"geht nach einem Tag in der Tiefkühltruhe kaputt",
	"geht kaputt, wenn man sich darauf setzt",
	"ist im Wasser nach 60 Sekunden kaputt",
	"überdauert Jahrzehnte",
	"gab es schon bei den alten Griechen",

	"Teil unserer Zivilisation",
	"ist oft im Büro",
	"gibt es auch im Wald oder Feld",
	"gibt es bei mir zu Hause",
	"kenne ich aus einem Märchen oder der Bibel",
	"gibt es in einem Wild West Film",
	"gibt es in einer Wohnung",
	"gibt in einer Sportanlage",
	"gibt es im Supermarkt",
	"wird meist im Winter verwendet",

	"Hängt manchmal an der Wand",
	"haben alle hier schon in der Hand gehabt",
	"kommuniziert oder hat was mit Kommunikation zu tun",
	"tritt meist in größeren Mengen auf",
	"wird am Fliessband produziert",
	"kostet weniger als 20 Euro",
	"wenn es fehlt, würde sich unser Leben stark verändern",
	"es gibt weniger davon als vor 100 Jahren",
	"riecht man",
	"habe ich in diesem Jahr noch nicht gesehen",
	"war früher teurer als heute",
	"gibt es in unterschiedlichen Farben",
	"kann für Kleinkinder gefährlich sein",
	"macht Geräusche, selbständig oder bei normalen Gebrauch",
	"kommt in Sprichwort oder Werbeslogan vor",
	"ist oft wärmer als die Umgebung",
	"damit kann man Wasser transportieren",
	"steht mit 4 Berührungspunkten auf dem Boden",
	"'Vorne' und 'hinten' sind hier kaum unterscheidbar",
	"kann ich innerhalb von 5 Minuten hierherbringen",
	"tragen Menschen an sich",
	"hat ungefähr die Größe eines Kartenspiels",
	"kann ohne Elektrizität kaum verwendet werden",
	"von Menschen erfunden",
	"darauf sind manchmal Buchstaben oder Zahlen",
	"gibt es in Miniatur als Spielzeug",
];