var cards = [
    {type:"Schatz",subtype:"A",count: 4, owner:""},
    {type:"Schatz",subtype:"B",count: 4, owner:""},
    {type:"Schatz",subtype:"C",count: 4, owner:""},
    {type:"Schatz",subtype:"D",count: 4, owner:""},
    {type:"Herz",subtype:"A",count: 2, owner:""},
    {type:"Herz",subtype:"B",count: 2, owner:""},
    {type:"Tür",subtype:"A",count: 2, owner:""},
    {type:"Tür",subtype:"B",count: 2, owner:""},
    {type:"Mob",subtype:"A",count: 4,dark:"dark", owner:""},
    {type:"Mob",subtype:"B",count: 4,dark:"dark", owner:""},
    {type:"Mob",subtype:"C",count: 4,dark:"dark", owner:""},
    {type:"Mob",subtype:"D",count: 4,dark:"dark", owner:""},
    {type:"Biss",subtype:"A",count: 3,dark:"dark", owner:""},
    {type:"Biss",subtype:"B",count: 3,dark:"dark", owner:""},
    {type:"Biss",subtype:"C",count: 3,dark:"dark", owner:""},
    {type:"Dieb",subtype:"A",count: 3,dark:"dark", owner:""},
    {type:"Dieb",subtype:"B",count: 3,dark:"dark", owner:""},
    {type:"Dieb",subtype:"C",count: 3,dark:"dark", owner:""},
]